apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctordetails
spec:
  selector:
    matchLabels:
      app: doctordetails
  replicas: 2
  template:
    metadata:
      labels:
        app: doctordetails
    spec:
      containers:
        - name: doctordetails
          image: sajithminds/
          ports:
            - containerPort: 80
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: doctordetails-serv
spec:
  selector:
    app: doctordetails
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80# The port exposed by the service
  type: NodePort # type of the service.