apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctordetails
spec:
  selector:
    matchLabels:
      app: doctordetails
  replicas: 2
  template:
    metadata:
      labels:
        app: doctordetails
    spec:
      containers:
        - name: doctordetails
          image: sajithminds/hospitalmanagement-app-1:1.0
          ports:
            - containerPort: 80
---

apiVersion: v1 
kind: Service
metadata: 
  name: doctordetails-serv
spec:
  selector:
    app: doctordetails
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: NodePort